// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProyectoCat.Models;
using System;

namespace ProyectoCat.Migrations
{
    [DbContext(typeof(ProyectoCatContext))]
    [Migration("20180302051331_Cliente")]
    partial class Cliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CédulaJurídica")
                        .IsRequired();

                    b.Property<string>("DirecciónFísica")
                        .IsRequired();

                    b.Property<int>("IdSector");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("PáginaWeb")
                        .IsRequired();

                    b.Property<int?>("SectorID");

                    b.HasKey("ID");

                    b.HasIndex("SectorID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ProyectoCat.Models.Sector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("Cliente", b =>
                {
                    b.HasOne("ProyectoCat.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID");
                });
#pragma warning restore 612, 618
        }
    }
}
